icons_format = "{icon}"

[icons]
icons = "awesome4"
[icons.overrides]
memory_mem = "\uf538" # 
cpu = "\uf2db"

[[block]]
block = "cpu"
interval = 2
format = " $icon $utilization ($frequency) "

[[block]]
block = "nvidia_gpu"
format = " $name: $utilization $power ($temperature) "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) ($icon_swap $swap_used_percents.eng(w:2)) "
format_alt = ""

[[block]]
block = "battery"
format = " $icon  $percentage $power ($time) "
empty_format = " $icon  $percentage $power ($time) "
missing_format = ""

[[block]]
block = "disk_space"
path = "$HOME"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon Home: $used.eng(w:2) / $total "

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %m/%d %r') "

[[block]]
block = "packages"
package_manager=["pacman"]
