export EDITOR="nvim"
# zsh highlight
source $HOME/.cache/wallust/zsh-highlight-color.sh
typeset -A ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=$color12,bold'
zstyle ':completion:*' completer _expand_alias _complete _ignored
source $HOME/.dotfiles/zsh/aliases.zsh
export PATH=$PATH:$HOME/.dotfiles/scripts/path/

