export ZSH="$HOME/.oh-my-zsh"
export HISTCONTROL=ignoreboth
ZSH_THEME="robbyrussell"
export EDITOR="nvim"

plugins=(branch vi-mode safe-paste zsh-interactive-cd)

get_alias() {
  printf '%s\n' $aliases[$1]
}

source $ZSH/oh-my-zsh.sh

# zsh highlight
typeset -A ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=$color12,bold'
# ZSH_HIGHLIGHT_STYLES[comment]='fg=$color9'

setopt AUTO_PUSHD                  # pushes the old directory onto the stack
setopt PUSHD_MINUS                 # exchange the meanings of '+' and '-'
setopt CDABLE_VARS                 # expand the expression (allows 'cd -2/tmp')
zstyle ':completion:*:directory-stack' list-colors '=(#b) #([0-9]#)*( *)==95=38;5;12'
zstyle ':completion:*' completer _expand_alias _complete _ignored
source $HOME/.dotfiles/zsh/aliases.zsh
export PATH=$PATH:$HOME/.dotfiles/scripts/path/
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
