#!/usr/bin/env bash
width="1920"
height="1080"

args=($@)
for ((i=0; i <= ${#args[@]}; i++)); do
    case ${args[i]} in
        "-w")
            width="${args[i+1]}"
        ;;
        "-h")
            height="${args[i+1]}"
        ;;
    esac
done


looking-glass-client spice:audio=yes input:rawMouse=true audio:micDefault=prompt win:size=$width"x"$height
